### ISSUE TITLE
Unify the folder structure

### ISSUE THREAD

**Issue by sebproell** [4C-multiphysics/4C#81]
_Original issue: https://gitlab.lrz.de/baci/baci/-/issues/1021_

## Description

This is a first suggestion by the taskforce modularization for the future directory structure of the code basis:

```
4C/
├── core/
│   ├── discretization/
│   │   ├── tests
│   │   ├── src
│   │   └── ...
│   ├── utils
│   ├── comm
│   └── ...
├── physics/
│   ├── solid/
│   │   ├── tests
│   │   ├── src/
│   │   │   ├── alg
│   │   │   ├── ele
│   │   │   ├── utils
│   │   │   └── ...
│   │   └── ...
│   ├── fluid
│   ├── scatra
│   ├── ale
│   └── ...
├── doc
├── app
├── tests/
│   └── input_files
├── cmake
└── ...
```

The idea is that the second directory layer (discretization, utils, comm, etc. // solid, fluid, etc.) represent individual targets that can be built and linked against, independent of the others. The inspiration for this structure is taken from the Trilinos project. 

The naming in "core" is chosen to represent related groups of functionality currently available in 4C, e.g. the content of lib, fem_general and others operating on the discretization will be grouped together in the directory "discretization". This will hopefully make it easier to navigate and search for functionality. 

Clarifying comment for the idea behind some directories:

- core: This contains modules that form the core of 4C's shared functionality. These modules are widely used within a lot or all physics implementations. We will move (and split up) folders like `lib`, `geometry`, `io`, ... here.
- physics: This contains modules that provide the implementation of everything physics-specific (elements, special time integration rules, special post-processing or output, ...). 
- app: This contains the files that are necessary to build the executable (4C-release/debug). In here, we would like to eventually selectively enable only a subset of all modules (user-selected). For now this should mainly contain the files from `global_full` and other files that gather all the options that are provided by the various physics (e.g. module_registry).

The modularization team would continue working with this structure in the current efforts to separate the core from the physics modules. 
Any feedback is welcome.

## Tasks

- [ ] Move unit tests closer to their source code
- [ ] Merge related directories, e.g. `fluid` and `fluid_ele`
- [ ] Use the internal `src` and `tests` structure
